worlds: [World, PlotWorld]
saveDataTickRate: 300
disableItemDrops: true
disableDispenserItemDrops: true
completeFill: true
maxRadius: 20
tntFillRadius: 5
fillingCap:
  default: 64
  vip: 128
  vipplus: 256
  owner: 99999