name: TNTFill
main: me.HeyAwesomePeople.TNTFill.TNTFill
softdepend: [PlotSquared, Multiverse-Core]
version: 1.0
commands:
  tntfill:
    description: Main command
  tntclear:
    description: Clears tnt within radius